AbCatCore/Controllers/CatalogItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AbCatCore.Helpers;
using AbCatCore.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace AbCatCore.Controllers
{
    public class CatalogItemsController : Controller
    {
        private readonly ICatalogDataContext _context;
        private readonly IConfiguration _configuration;

        private static string currentGid = null;
        public CatalogItemsController(ICatalogDataContext context, IConfiguration configuration)
        {
            _context = context;
            _configuration = configuration;
        }

        // GET: CatItem
        public ActionResult Index()
        {
            return View(_context.Items);
        }

        // GET: CatItem
        public ActionResult Screen()
        {
            var item = _context.Items.FirstOrDefault(x => x.sGID == currentGid);
            if (item != null)
            {
                MovieSceneInfo data = new MovieSceneInfo();
                data.PositionStart = 30;
                data.PositionEnd = 35;
                return View(data);
            }
            return new EmptyResult();
        }

        // GET: CatItem/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CatItem/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CatItem/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CatItem/Edit/5
        public ActionResult Edit(string sGID)
        {
            //return View();
            try
            {
                // TODO: Add update logic here
                currentGid = sGID;
                return RedirectToAction(nameof(Screen));
            }
            catch
            {
                return View();
            }
        }

        // POST: CatItem/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string sGID, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CatItem/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CatItem/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AbCatCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AbCatCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mx-0 my-0" style="max-height:30px">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ABCAT</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CatalogItems" asp-action="Index">Catalog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CatalogItems" asp-action="Screen">Screen</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main">
            <div class="row">
                <div class="col-sm-8">
                    @RenderBody()
                </div>
                <div class="col-sm-4">
                    @*@await Component.InvokeAsync("VideoWidget");*@
                </div>
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - AbCatCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    @*<script src="~/js/site.js" asp-append-version="true"></script>'*@
    
    @RenderSection("js", required: false)
</body>
</html>